version: "3.9"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - api_data:/app/data
      - ./api/demo_data:/app/demo_data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/tracelite.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - INIT_DEMO_DATA=true
    command: >
      sh -c "
        python -c 'import asyncio; from app.demo_data.init_demo import init_demo_data; asyncio.run(init_demo_data())' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "5173:80"  # Map port 5173 to nginx port 80 for compatibility
    environment:
      - VITE_API_BASE_URL=http://65.20.74.233:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  api_data:
    driver: local
