version: "3.9"
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
      - api_data_dev:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/tracklite.db
      - SECRET_KEY=dev-secret-key-change-in-production
      - INIT_DEMO_DATA=true
    command: >
      sh -c "
        python -c 'import asyncio; from demo_data.init_demo import init_demo_data; asyncio.run(init_demo_data())' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  api_data_dev:
    driver: local
