version: "3.9"
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: ./web
    volumes:
      - ./web:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    command: npm run dev -- --host